# Generated by Django 4.0.4 on 2022-05-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('salon', models.CharField(max_length=10)),
                ('horario', models.CharField(max_length=200)),
                ('id_profesor', models.IntegerField()),
            ],
        ),
    ]
