# Generated by Django 4.0.4 on 2022-05-24 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('id_signatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura')),
            ],
        ),
    ]
