# Generated by Django 4.0.4 on 2022-05-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('asignaturas', '0002_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='id_estudiante',
        ),
        migrations.AddField(
            model_name='clase',
            name='id_estudiante',
            field=models.ManyToManyField(to='estudiante.estudiante'),
        ),
    ]
