# Generated by Django 4.0.4 on 2022-05-24 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('asignaturas', '0003_remove_clase_id_estudiante_clase_id_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase',
            name='id_estudiante',
        ),
        migrations.AddField(
            model_name='clase',
            name='id_estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
            preserve_default=False,
        ),
    ]
